apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: consumer
spec:
  rabbitmqClusterReference:
    name: shared-mq
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: consumer-permission
spec:
  vhost: "shared-mq-vhost"
  userReference:
    name: consumer
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: shared-mq